fix: deploy-ci-history (#3)
* fix: deploy-ci-history

* fix: ci.yml, pr-coverage.yml e deploy-ci-history.yml

* fix: ci.yml, pr-coverage.yml e deploy-ci-history.yml

* fix: ci.yml - part 2

* fix: ci.yml - part 3

* fix: pr-coverage - part 1

* fix: ci

* fix: ci 2

* fix: ci 3

* fix: ci 4

* fix: ci 5

* fix: ci 6

* fix: ci 7

* fix: ci 7

* fix: ci 8

* fix: ci 9

* fix: pr-coverage 2

* fix: pr-coverage 3

* fix: pr-coverage 4

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -95,7 +95,7 @@ jobs:
       - name: Upload coverage artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: history.json
+          name: coverage
           path: coverage
 
       - name: Write JaCoCo snapshot
@@ -114,4 +114,17 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: ci-history
-          path: ci-history
+          path: ${{ github.workspace }}/ci-history
+
+      - name: Debug CI history folder
+        run: |
+          echo "Contents of .ci-history:"
+          ls -R .ci-history || echo "Folder .ci-history not found"
+      - name: Debug absolute paths
+        run: |
+          echo "Workspace is: ${{ github.workspace }}"
+          echo "Listing workspace:"
+          ls -a ${{ github.workspace }}
+          echo "Listing ci-history:"
+          ls -R ${{ github.workspace }}/.ci-history || echo "ci-history not found here"
+
